import Head from 'next/head';
import Image from 'next/image';
import formImage from '../public/form.png'
import { useFormik } from 'formik';
import * as Yup from 'yup'
import {useRouter } from 'next/router';
import {motion as m} from 'framer-motion';

// 39.22

export default function Home() {

  // router
  const router = useRouter();


  // formik logics
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "Cd. de México",
      terms: "",
    },// Validate form

    validationSchema: Yup.object({
      name: Yup.string()
        .min(3, "El nombre debe tener mínimo 4 caracteres.")
        .max(20, "El nombre no debe tener mas de 20 caracteres.")
        .required("El nombre es requerido"),
      email: Yup.string()
        .email("Correo invalido")
        .required("El correo es requerido"),
      terms: Yup.array().required("Los términos del servicio deben ser aceptados"),
    }),

    onSubmit: (values) => {
      console.log("form submitted");
      router.push({pathname: '/success', query: values})
      
    },


  })

  console.log(formik.errors)

  return (

    <m.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className='abs'>
      <Head>
        <title>Formulario con React y Next.js</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/public/form.svg' />
      </Head>

      <main className=' h-screen items-center flex  justify-center'>
        <form onSubmit={formik.handleSubmit}
          className="bg-white flex rounded-lg w-4/5 font-latoRegular">
          <div className='flex-1 text-gray-700 p-5'>
            <h1 className='text-3xl pb-2 font-latoBold'>Comencemos👋</h1>
            <p className='text-lg text-gray-500'>Únete a nuestra plataforma de aprendizaje electrónico hoy y desbloquee más de 500 cursos y activos digitales listos para descargar.</p>

            <div className='mt-6'>
              {/* name input */}
              <div className='pb-4'>
                <label className={`block font-latoBold text-sm pb-2 ${formik.touched.name && formik.errors.name ? 'text-red-400' : ''}`} htmlFor="name">
                  {formik.touched.name && formik.errors.name ? formik.errors.name : 'Nombre'}
                </label>
                <input className='border-2 border-gray-500 p-2 rounded-md w-4/5 focus:border-teal-500 focus:ring-teal-500'
                  type="text"
                  name='name'
                  placeholder='Ingresa tu nombre'
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>

              {/* eamil input */}
              <div className='pb-4'>
                <label className={`block font-latoBold text-sm pb-2 ${formik.touched.email && formik.errors.email ? 'text-red-400' : ''}`} htmlFor="email"> {formik.touched.email && formik.errors.email ? formik.errors.email : 'Correo electrónico '} </label>
                <input className='border-2 border-gray-500 p-2 rounded-md w-4/5 focus:border-teal-500 focus:ring-teal-500'
                  type="email"
                  name='email'
                  placeholder='Ingresa tu correo'
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>

              {/* country input */}
              <div className='pb-4'>
                <label className='block font-latoBold text-sm pb-2' htmlFor="country">Cuidad</label>
                <select
                  value={formik.values.country}
                  onChange={formik.handleChange}
                  name="contry"
                  className='border-2 border-gray-500 p-2 rounded-md w-4/5 focus:border-teal-500 focus:ring-teal-500'>
                  <option>Oaxaca</option>
                  <option>Monterrey</option>
                  <option>Queretaro</option>
                  <option>Merida</option>
                  <option>Cd. de México</option>
                </select>
              </div>

              {/* terms of services */}
              <div className='pb-4'>
                <label className={`block font-latoBold text-sm pb-2 ${formik.touched.terms && formik.errors.terms ? 'text-red-400' : ''}`} htmlFor="terms"> {formik.touched && formik.errors.terms ? formik.errors.terms : 'Terminos de servicio'} </label>
                <div className='flex items-center gap-2'>
                  <input
                    value='checked'
                    type="checkbox"
                    name='terms'
                    className='h-5 w-5 text-teal-500 border-2  background-gray-500 focus:border-teal-500 focus:ring-teal-500'
                    onChange={formik.handleChange}
                  />
                  <p className='text-sm font-latoBold text-gray-500'> Acepto los Términos y Servicios que mis datos no serán tomados ni vendidos a terceros.</p>
                </div>
              </div>

              <button type='submit' className='bg-teal-500 font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full'>¡Empieza a aprender hoy!</button>
            </div>
          </div>

          <div className='relative  flex-1 hidden md:block' >
            <Image src={formImage} alt='form-learn' priority fill className='object-cover rounded-r-lg hidden md:block' />
          </div>

        </form>
      </main>
    </m.div>

  );
}
